export const adminDashboardData = {
  kpis: [
    {
      label: "ENROLLED STUDENTS",
      value: "1,247",
      trend: "+5.2% ↑",
      trendColor: "#4ADE80",
    },
    {
      label: "FACULTY MEMBERS",
      value: "86",
      trend: "Steady",
      trendColor: "#C2C6D6",
    },
    {
      label: "PENDING REGISTRATIONS",
      value: "34",
      trend: "Needs Review",
      trendColor: "#FFB4AB",
    },
    {
      label: "SYSTEM UPTIME",
      value: "99.8%",
      trend: "Optimal",
      trendColor: "#4CD7F6",
    },
  ],
  enrollmentTrends: [
    { month: "JAN", count: 40 },
    { month: "FEB", count: 70 },
    { month: "MAR", count: 100 },
    { month: "APR", count: 150 },
    { month: "MAY", count: 190 },
    { month: "JUN", count: 120 },
    { month: "JUL", count: 80 },
    { month: "AUG", count: 60 },
    { month: "SEP", count: 170 },
    { month: "OCT", count: 200 },
  ],
  quickManagement: [
    {
      title: "User Management",
      subtitle: "Manage all platform users",
      iconColor: "#ADC6FF",
      iconBg: "rgba(173, 198, 255, 0.1)",
      route: "/admin/users",
    },
    {
      title: "Course Management",
      subtitle: "Configure course offerings",
      iconColor: "#4CD7F6",
      iconBg: "rgba(76, 215, 246, 0.1)",
      route: "/admin/courses",
    },
    {
      title: "Semester Config",
      subtitle: "Spring 2025 active",
      iconColor: "#BCC7DE",
      iconBg: "rgba(188, 199, 222, 0.1)",
      route: "/admin/semesters",
    },
  ],
  auditTrail: [
    {
      id: 1,
      timestamp: "2025-06-28 10:45:22",
      admin: "Admin Sarah J.",
      action: "UPDATE_SEMESTER_RULES",
      entity: "Spring 2025",
      status: "SUCCESS",
    },
    {
      id: 2,
      timestamp: "2025-06-28 09:13:09",
      admin: "System Automator",
      action: "BULK_ENROLLMENT_SYNC",
      entity: "CS Dept (120 records)",
      status: "SUCCESS",
    },
    {
      id: 3,
      timestamp: "2025-06-27 23:22:41",
      admin: "Security Shield",
      action: "LOGIN_FAILURE_THRESHOLD",
      entity: "IP: 192.168.1.45",
      status: "BLOCKED",
    },
    {
      id: 4,
      timestamp: "2025-06-27 15:30:10",
      admin: "Admin Mike R.",
      action: "COURSE_OVERRIDE_APPROVED",
      entity: "#2025-4071 (CS-301)",
      status: "PENDING_SYNC",
    },
  ],
};
