export const advisingSessions = [
  {
    _id: 'as001',
    studentId: 'stu001',
    advisorId: 'adv001',
    semesterId: 'sem002',
    notes: 'Student is on track. Recommended taking CS301 next semester. GPA is solid.',
    status: 'completed',
    date: '2026-06-20',
    time: '10:00',
    type: 'Degree Audit',
    location: 'Zoom Conference',
    title: 'Degree Audit: Ahmed Student',
  },
  {
    _id: 'as002',
    studentId: 'stu002',
    advisorId: 'adv001',
    semesterId: 'sem002',
    notes: '',
    status: 'scheduled',
    date: '2026-06-28',
    time: '14:00',
    type: 'Registration Review',
    location: 'Office 301A',
    title: 'Registration Review: Sara Student',
  },
  {
    _id: 'as003',
    studentId: 'stu001',
    advisorId: 'adv001',
    semesterId: 'sem001',
    notes: 'Discussed study plan for Year 3. Student wants to focus on database and web development.',
    status: 'completed',
    date: '2026-05-15',
    time: '11:00',
    type: 'Study Plan',
    location: 'Office 402B',
    title: 'Study Plan: Ahmed Student',
  },
  {
    _id: 'as004',
    studentId: 'stu005',
    advisorId: 'adv001',
    semesterId: 'sem002',
    notes: 'Senior review for graduation requirements.',
    status: 'scheduled',
    date: '2026-06-29',
    time: '09:00',
    type: 'Senior Review',
    location: 'Zoom Conference',
    title: 'Degree Audit: Leo Thompson',
  },
  {
    _id: 'as005',
    studentId: 'stu006',
    advisorId: 'adv001',
    semesterId: 'sem002',
    notes: 'Probation follow-up meeting.',
    status: 'scheduled',
    date: '2026-06-29',
    time: '11:00',
    type: 'Probation Meeting',
    location: 'Office 402B',
    title: 'Probation Meeting: Elena Rossi',
  },
  {
    _id: 'as006',
    studentId: 'stu007',
    advisorId: 'adv001',
    semesterId: 'sem002',
    notes: 'New transfer student onboarding.',
    status: 'scheduled',
    date: '2026-06-29',
    time: '14:00',
    type: 'Transfer Onboarding',
    location: 'Large Lecture Hall',
    title: 'New Transfer Onboarding',
  },
];
