export const complaints = [
  {
    _id: "4920",
    ticketNumber: "#4920",
    category: "TECHNICAL ISSUE",
    categoryColor: "text-[#4CD7F6]",
    title: "Portal Login Loop",
    snippet: "Student unable to bypass MFA screen after secondary auth...",
    fullDescription: "I am trying to log in to the portal for course registration but I'm getting stuck in an infinite loop. After entering my password, it asks for the MFA code. I enter the code correctly, and instead of taking me to the dashboard, it redirects me back to the password screen. I've cleared my cache and tried three different browsers.",
    status: "IN-PROGRESS",
    statusBadge: "bg-[#03B5D3] text-[#00424E]",
    timeAgo: "2m ago",
    dateFormatted: "Oct 12, 2023 - 09:12 AM",
    student: {
      name: "Ahmed Raza",
      studentId: "22-4012",
      major: "Computer Science, Year 3",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80",
      previousTickets: [
        { title: "ID Card Issue", status: "CLOSED" },
        { title: "Library Access", status: "CLOSED" },
      ],
      auditLog: [
        { time: "09:12", event: "Ticket Opened" },
        { time: "10:01", event: "Assigned to IT" },
        { time: "10:45", event: "Admin Response" },
      ],
    },
    internalNote: {
      author: "IT System Admin",
      note: "Checking session token logs. There seems to be a mismatch in the redirect URL for the MFA success callback on the production environment.",
    },
    messages: [
      {
        id: 1,
        sender: "Ahmed Raza",
        time: "09:12 AM",
        text: "I am trying to log in to the portal for course registration but I'm getting stuck in an infinite loop. After entering my password, it asks for the MFA code. I enter the code correctly, and instead of taking me to the dashboard, it redirects me back to the password screen. I've cleared my cache and tried three different browsers.",
        isStudent: true,
      },
    ],
    agent: "Unassigned",
  },
  {
    _id: "4919",
    ticketNumber: "#4919",
    category: "GRADE APPEAL",
    categoryColor: "text-[#BCC7DE]",
    title: "Final Grade Discrepancy",
    snippet: "Requesting review for CSE-401 Project C marking...",
    fullDescription: "My final grade for CSE-401 shows 82 (B), but when I sum my lab scores, midterm, and Project C submission, my total should be 89 (B+). I submitted the project on time via the repository link.",
    status: "UNASSIGNED",
    statusBadge: "bg-[#323537] text-[#C2C6D6]",
    timeAgo: "45m ago",
    dateFormatted: "Oct 12, 2023 - 08:30 AM",
    student: {
      name: "Sara Malik",
      studentId: "21-8932",
      major: "Software Engineering, Year 4",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=300&q=80",
      previousTickets: [
        { title: "Course Override", status: "CLOSED" },
      ],
      auditLog: [
        { time: "08:30", event: "Ticket Opened" },
        { time: "08:35", event: "Automated Routing" },
      ],
    },
    internalNote: null,
    messages: [
      {
        id: 1,
        sender: "Sara Malik",
        time: "08:30 AM",
        text: "My final grade for CSE-401 shows 82 (B), but when I sum my lab scores, midterm, and Project C submission, my total should be 89 (B+). I submitted the project on time via the repository link.",
        isStudent: true,
      },
    ],
    agent: "Unassigned",
  },
  {
    _id: "4299",
    ticketNumber: "#4299",
    category: "ENROLLMENT BUG",
    categoryColor: "text-[#4D8EFF]",
    title: "Pre-requisite Override",
    snippet: "System blocking enrollment despite credit completion...",
    fullDescription: "I completed MATH-201 during the summer semester at our partner institute, and my transcript was transferred. However, the system is blocking me from enrolling in MATH-301 stating prerequisite incomplete.",
    status: "HIGH PRIORITY",
    statusBadge: "bg-[#93000A] text-[#FFDAD6]",
    timeAgo: "3h ago",
    dateFormatted: "Oct 12, 2023 - 06:15 AM",
    student: {
      name: "Zubair Khan",
      studentId: "23-1104",
      major: "Data Science, Year 2",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80",
      previousTickets: [],
      auditLog: [
        { time: "06:15", event: "Ticket Opened" },
        { time: "07:00", event: "Flagged High Priority by Dean" },
      ],
    },
    internalNote: {
      author: "Registrar Office",
      note: "Transfer credit verification is complete. Need sysadmin to clear the pre-req hold flag in the database.",
    },
    messages: [
      {
        id: 1,
        sender: "Zubair Khan",
        time: "06:15 AM",
        text: "I completed MATH-201 during the summer semester at our partner institute, and my transcript was transferred. However, the system is blocking me from enrolling in MATH-301 stating prerequisite incomplete.",
        isStudent: true,
      },
    ],
    agent: "Registrar",
  },
  {
    _id: "4282",
    ticketNumber: "#4282",
    category: "TECHNICAL ISSUE",
    categoryColor: "text-[#4CD7F6]",
    title: "PDF Generation Error",
    snippet: "Transcript export failing with 500 error on mobile...",
    fullDescription: "Whenever I try to download my unofficial transcript PDF on iOS Safari or Chrome, the server returns an HTTP 500 internal server error.",
    status: "RESOLVED",
    statusBadge: "bg-[#323537] text-[#C2C6D6]",
    timeAgo: "1d ago",
    dateFormatted: "Oct 11, 2023 - 02:40 PM",
    student: {
      name: "Mariam Al-Sayed",
      studentId: "20-5510",
      major: "Information Technology, Year 4",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80",
      previousTickets: [
        { title: "Wifi Authentication", status: "CLOSED" },
      ],
      auditLog: [
        { time: "14:40", event: "Ticket Opened" },
        { time: "15:20", event: "Assigned to IT" },
        { time: "16:00", event: "Resolved & Closed" },
      ],
    },
    internalNote: {
      author: "DevOps Team",
      note: "Patched headless Chromium PDF generator timeout issue. Student verified resolution.",
    },
    messages: [
      {
        id: 1,
        sender: "Mariam Al-Sayed",
        time: "02:40 PM",
        text: "Whenever I try to download my unofficial transcript PDF on iOS Safari or Chrome, the server returns an HTTP 500 internal server error.",
        isStudent: true,
      },
      {
        id: 2,
        sender: "IT Support",
        time: "04:00 PM",
        text: "Hello Mariam, we have resolved the PDF generation timeout on our server. Please try downloading your transcript again!",
        isStudent: false,
      },
    ],
    agent: "IT Support",
  },
];
