export const departments = [
  {
    _id: 'd001',
    name: 'Computer Science',
    code: 'CS',
    badge: 'STEM CORE',
    badgeColor: 'blue',
    iconType: 'code',
    facultyCount: 84,
    studentCount: 1240,
    head: {
      name: 'Dr. Elias Thorne',
      title: 'PhD, Machine Learning',
      avatar: 'ET',
      avatarColor: 'bg-[#03B5D3]/20 text-[#4CD7F6] border border-[#4CD7F6]/20',
      status: 'assigned',
    },
  },
  {
    _id: 'd002',
    name: 'Mechanical Engineering',
    code: 'ME',
    badge: 'RESEARCH LEAD',
    badgeColor: 'slate',
    iconType: 'gear',
    facultyCount: 112,
    studentCount: 890,
    head: {
      name: 'Dr. Sarah Jenkins',
      title: 'MSc, Robotics Engineering',
      avatar: 'SJ',
      avatarColor: 'bg-[#ADC6FF]/20 text-[#ADC6FF] border border-[#ADC6FF]/20',
      status: 'assigned',
    },
  },
  {
    _id: 'd003',
    name: 'Arts & Design',
    code: 'AD',
    badge: 'HIGH GROWTH',
    badgeColor: 'red',
    iconType: 'palette',
    facultyCount: 45,
    studentCount: 650,
    head: {
      name: 'Position Vacant',
      title: 'Interim: Faculty Board',
      avatar: 'PV',
      avatarColor: 'bg-[#8691A7]/20 text-[#BCC7DE] border border-[#BCC7DE]/20',
      status: 'vacant',
    },
  },
  {
    _id: 'd004',
    name: 'Business Admin',
    code: 'BA',
    badge: 'ENTERPRISE',
    badgeColor: 'blue',
    iconType: 'briefcase',
    facultyCount: 68,
    studentCount: 1150,
    head: {
      name: 'Dr. Robert Vance',
      title: 'PhD, Strategic Management',
      avatar: 'RV',
      avatarColor: 'bg-[#4F378A]/30 text-[#E9DDFF] border border-[#E9DDFF]/20',
      status: 'assigned',
    },
  },
];

export const pendingAllocations = [
  {
    _id: 'pa001',
    name: 'Dr. Marcus Kane',
    title: 'Senior Lecturer',
    specialization: 'Cybersecurity & Forensics',
    status: 'UNDER REVIEW',
    statusColor: 'cyan',
    avatar: 'MK',
    avatarColor: 'bg-[#4D8EFF]/20 text-[#4D8EFF] border border-[#4D8EFF]/30',
  },
  {
    _id: 'pa002',
    name: 'Prof. Linda Low',
    title: 'Visiting Fellow',
    specialization: 'Structural Engineering',
    status: 'ON HOLD',
    statusColor: 'red',
    avatar: 'LL',
    avatarColor: 'bg-[#8691A7]/20 text-[#BCC7DE] border border-[#BCC7DE]/30',
  },
];
