export const students = [
  {
    _id: 'stu001',
    userId: 'u001',
    departmentId: 'd001',
    advisorId: 'adv001',
    GPA: 3.45,
    level: 3,
    name: 'Ahmed Student',
    email: 'ahmed.student@morshed.edu',
    universityId: '20210001',
    departmentName: 'Computer Science',
    program: 'B.Sc. Computer Science',
  },
  {
    _id: 'stu002',
    userId: 'u002',
    departmentId: 'd002',
    advisorId: 'adv001',
    GPA: 2.89,
    level: 2,
    name: 'Sara Student',
    email: 'sara.student@morshed.edu',
    universityId: '20210002',
    departmentName: 'Computer Science',
    program: 'B.Sc. Computer Science',
  },
  {
    _id: 'stu003',
    userId: 'u007',
    departmentId: 'd001',
    advisorId: 'adv001',
    GPA: 1.85,
    level: 1,
    name: 'Moamen Ahmed',
    email: 'moamen@morshed.edu',
    universityId: '20210005',
    departmentName: 'Computer Science',
    program: 'B.Sc. Computer Science',
  },
  {
    _id: 'stu004',
    userId: 'u008',
    departmentId: 'd001',
    advisorId: 'adv001',
    GPA: 2.15,
    level: 2,
    name: 'Marcus Knight',
    email: 'marcus@morshed.edu',
    universityId: '20230011',
    departmentName: 'Computer Science',
    program: 'B.Sc. Computer Science',
  },
  {
    _id: 'stu005',
    userId: 'u009',
    departmentId: 'd002',
    advisorId: 'adv001',
    GPA: 3.75,
    level: 4,
    name: 'Leo Thompson',
    email: 'leo.thompson@morshed.edu',
    universityId: '20200007',
    departmentName: 'Information Technology',
    program: 'B.Sc. Information Technology',
  },
  {
    _id: 'stu006',
    userId: 'u010',
    departmentId: 'd001',
    advisorId: 'adv001',
    GPA: 2.45,
    level: 3,
    name: 'Elena Rossi',
    email: 'elena.rossi@morshed.edu',
    universityId: '20220019',
    departmentName: 'Computer Science',
    program: 'B.Sc. Computer Science',
  },
  {
    _id: 'stu007',
    userId: 'u011',
    departmentId: 'd003',
    advisorId: 'adv001',
    GPA: 3.1,
    level: 1,
    name: 'Sarah Chen',
    email: 'sarah.chen@morshed.edu',
    universityId: '20240003',
    departmentName: 'Mathematics',
    program: 'B.Sc. Mathematics',
  },
];
