export const users = [
  {
    _id: 'u001',
    universityId: '20210001',
    idNumber: 'USR-990214',
    name: 'Ahmed Al-Farsi',
    email: 'ahmed.student@morshed.edu',
    password: 'hashed_password',
    role: 'student',
    department: 'Business Admin',
    isActive: true,
  },
  {
    _id: 'u002',
    universityId: '20210002',
    idNumber: 'USR-773402',
    name: 'Emily Watson',
    email: 'emily.w@student.morshed.edu',
    password: 'hashed_password',
    role: 'student',
    department: 'Mathematics',
    isActive: true,
  },
  {
    _id: 'u003',
    universityId: 'P001',
    idNumber: 'USR-882910',
    name: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@morshed.edu',
    password: 'hashed_password',
    role: 'professor',
    department: 'Computer Science',
    isActive: true,
  },
  {
    _id: 'u004',
    universityId: 'P002',
    idNumber: 'USR-881004',
    name: 'Dr. Fatima Zahra',
    email: 'dr.fatima@morshed.edu',
    password: 'hashed_password',
    role: 'professor',
    department: 'Computer Science',
    isActive: true,
  },
  {
    _id: 'u005',
    universityId: 'A001',
    idNumber: 'USR-112003',
    name: 'Linda Miller',
    email: 'linda.m@morshed.edu',
    password: 'hashed_password',
    role: 'advisor',
    department: 'Mathematics',
    isActive: true, 
  },
  {
    _id: 'u006',
    universityId: 'ADM001',
    idNumber: 'USR-445100',
    name: 'Marcus Chen',
    email: 'admin@morshed.edu',
    password: 'hashed_password',
    role: 'admin',
    department: 'IT Services',
    isActive: true,
  },
  {
    _id: 'u007',
    universityId: '20210005',
    idNumber: 'USR-332190',
    name: 'Moamen Ali',
    email: 'moamen@morshed.edu',
    password: 'hashed_password',
    role: 'student',
    department: 'Computer Science',
    isActive: true,
  },
  {
    _id: 'u008',
    universityId: '20230011',
    idNumber: 'USR-441092',
    name: 'Marcus Vance',
    email: 'marcus.v@morshed.edu',
    password: 'hashed_password',
    role: 'student',
    department: 'Business Admin',
    isActive: true,
  },
  {
    _id: 'u009',
    universityId: '20200007',
    idNumber: 'USR-550182',
    name: 'Leo Thompson',
    email: 'leo.thompson@morshed.edu',
    password: 'hashed_password',
    role: 'student',
    department: 'Physics',
    isActive: true,
  },
  {
    _id: 'u010',
    universityId: '20220019',
    idNumber: 'USR-661023',
    name: 'Elena Rossi',
    email: 'elena.rossi@morshed.edu',
    password: 'hashed_password',
    role: 'student',
    department: 'Mathematics',
    isActive: false,
  },
  {
    _id: 'u011',
    universityId: '20240003',
    idNumber: 'USR-771904',
    name: 'Sarah Chen',
    email: 'sarah.chen@morshed.edu',
    password: 'hashed_password',
    role: 'student',
    department: 'Computer Science',
    isActive: true,
  },
];
