export const users = [
  {
    _id: 'u001',
    universityId: '20210001',
    email: 'ahmed.student@morshed.edu',
    password: 'hashed_password',
    role: 'student',
    isActive: true,
  },
  {
    _id: 'u002',
    universityId: '20210002',
    email: 'sara.student@morshed.edu',
    password: 'hashed_password',
    role: 'student',
    isActive: true,
  },
  {
    _id: 'u003',
    universityId: 'P001',
    email: 'dr.khaled@morshed.edu',
    password: 'hashed_password',
    role: 'professor',
    isActive: true,
  },
  {
    _id: 'u004',
    universityId: 'P002',
    email: 'dr.fatima@morshed.edu',
    password: 'hashed_password',
    role: 'professor',
    isActive: true,
  },
  {
    _id: 'u005',
    universityId: 'A001',
    email: 'dr.omar.advisor@morshed.edu',
    password: 'hashed_password',
    role: 'advisor',
    isActive: true,
  },
  {
    _id: 'u006',
    universityId: 'ADM001',
    email: 'admin@morshed.edu',
    password: 'hashed_password',
    role: 'admin',
    isActive: true,
  },
];
