import { ROUTES } from "../../routes/RoutePaths";
import {
  LayoutDashboard,
  BookOpen,
  CalendarCheck,
  Calendar,
  ScrollText,
  GraduationCap,
  UserCheck,
  MessageSquare,
  CreditCard,
  ClipboardCheck,
  User,
  Bell,
  Calculator,
  Settings,
  Users,
  FileText,
  ClipboardList,
  AlertTriangle,
  BarChart3,
  BookMarked,
  Building2,
  ShieldCheck,
  CreditCard as CreditCardIcon,
} from "lucide-react";

export const roleNavConfig = {
  student: [
    { to: ROUTES.STUDENT.DASHBOARD, label: "Dashboard", icon: LayoutDashboard },
    { to: ROUTES.STUDENT.ENROLLMENT, label: "Course Enrollment", icon: BookOpen },
    { to: ROUTES.STUDENT.SEMESTER_REGISTRATION, label: "Semester Registration", icon: CalendarCheck },
    { to: ROUTES.STUDENT.SCHEDULE, label: "Schedule", icon: Calendar },
    { to: ROUTES.STUDENT.EXAM_SCHEDULE, label: "Exam Schedule", icon: ScrollText },
    { to: ROUTES.STUDENT.TRANSCRIPT, label: "Transcript", icon: GraduationCap },
    { to: ROUTES.STUDENT.STUDY_PLAN, label: "Study Plan", icon: ClipboardCheck },
    { to: ROUTES.STUDENT.ADVISING, label: "Advising", icon: UserCheck },
    { to: ROUTES.STUDENT.COMPLAINTS, label: "Complaints", icon: MessageSquare },
    { to: ROUTES.STUDENT.PAYMENTS, label: "Payments", icon: CreditCard },
    { to: ROUTES.STUDENT.ATTENDANCE, label: "Attendance", icon: ClipboardCheck },
    { to: ROUTES.STUDENT.PROFILE, label: "Profile", icon: User },
    { to: ROUTES.STUDENT.NOTIFICATIONS, label: "Notifications", icon: Bell },
    { to: ROUTES.STUDENT.GPA_CALCULATOR, label: "GPA Calculator", icon: Calculator },
    { to: ROUTES.STUDENT.SETTINGS, label: "Settings", icon: Settings },
  ],
  professor: [
    { to: ROUTES.PROFESSOR.DASHBOARD, label: "Dashboard", icon: LayoutDashboard },
    { to: ROUTES.PROFESSOR.COURSES, label: "My Courses", icon: BookOpen },
    { to: ROUTES.PROFESSOR.ASSIGNMENTS, label: "Assignments", icon: ClipboardList },
    { to: ROUTES.PROFESSOR.ATTENDANCE, label: "Attendance", icon: ClipboardCheck },
    { to: ROUTES.PROFESSOR.GRADES, label: "Grades", icon: BarChart3 },
    { to: ROUTES.PROFESSOR.STUDENTS, label: "Students", icon: Users },
    { to: ROUTES.PROFESSOR.SCHEDULE, label: "Schedule", icon: Calendar },
    { to: ROUTES.PROFESSOR.NOTIFICATIONS, label: "Notifications", icon: Bell },
  ],
  advisor: [
    { to: ROUTES.ADVISOR.DASHBOARD, label: "Dashboard", icon: LayoutDashboard },
    { to: ROUTES.ADVISOR.STUDENTS, label: "Student List", icon: Users },
    { to: ROUTES.ADVISOR.SESSIONS, label: "Advising Sessions", icon: UserCheck },
    { to: ROUTES.ADVISOR.GRADUATION, label: "Graduation Requirements", icon: GraduationCap },
    { to: ROUTES.ADVISOR.ISSUES, label: "Issue Resolution", icon: AlertTriangle },
  ],
  admin: [
    { to: ROUTES.ADMIN.DASHBOARD, label: "Dashboard", icon: LayoutDashboard },
    { to: ROUTES.ADMIN.USERS, label: "User Management", icon: Users },
    { to: ROUTES.ADMIN.COURSES, label: "Course Management", icon: BookMarked },
    { to: ROUTES.ADMIN.DEPARTMENTS, label: "Departments", icon: Building2 },
    { to: ROUTES.ADMIN.SEMESTERS, label: "Semesters", icon: Calendar },
    { to: ROUTES.ADMIN.COMPLAINTS, label: "Complaints", icon: MessageSquare },
    { to: ROUTES.ADMIN.REGISTRATION, label: "Registration Control", icon: ShieldCheck },
    { to: ROUTES.ADMIN.REPORTS, label: "Reports & Analytics", icon: BarChart3 },
    { to: ROUTES.ADMIN.POLICIES, label: "Academic Policies", icon: FileText },
    { to: ROUTES.ADMIN.SETTINGS, label: "Settings", icon: Settings },
  ],
};
